/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElTreeV2: typeof import('element-plus/es')['ElTreeV2']
    IEpDocument: typeof import('~icons/ep/document')['default']
    IEpHomeFilled: typeof import('~icons/ep/home-filled')['default']
    IEpLocation: typeof import('~icons/ep/location')['default']
    IEpMenu: typeof import('~icons/ep/menu')['default']
    IEpSetting: typeof import('~icons/ep/setting')['default']
    README: typeof import('./../components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./../components/TheCounter.vue')['default']
    TheFooter: typeof import('./../components/TheFooter.vue')['default']
    TheInput: typeof import('./../components/TheInput.vue')['default']
  }
}
